name: Deploy Swift Package

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode.app
    
    - name: Build Package
      run: swift build
    
    - name: Run Tests
      run: swift test
    
    - name: Create git tag if not exists
      if: github.event_name == 'workflow_dispatch'
      run: |
        VERSION=$(cat VERSION)
        git config user.name hyodotdev
        git config user.email hyo@hyo.dev
        
        # Check if tag exists on remote
        if git ls-remote --tags origin | grep -q "refs/tags/$VERSION"; then
          echo "Tag $VERSION already exists on remote, skipping..."
        else
          # Create tag locally if not exists
          if ! git rev-parse "refs/tags/$VERSION" >/dev/null 2>&1; then
            git tag $VERSION
          fi
          # Push tag
          git push origin $VERSION
        fi
    
    - name: Verify Package
      run: |
        swift package show-dependencies
        swift package describe