name: Deploy to CocoaPods

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Select Xcode
      run: |
        sudo xcode-select -s /Applications/Xcode.app
    
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
        bundler-cache: true
    
    - name: Install CocoaPods
      run: |
        gem install cocoapods
    
    - name: Validate Podspec
      run: |
        pod lib lint openiap.podspec --allow-warnings
    
    - name: Deploy to CocoaPods Trunk
      if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        COCOAPODS_VALIDATOR_SKIP_XCODEBUILD: 1
      run: |
        pod trunk push openiap.podspec --allow-warnings